/**
 * Care profile seed data — Dirt & Leaf
 * ====================================
 *
 * WHAT THIS FILE IS
 * ------------------
 * This is the species-level horticultural reference data behind every
 * plant's watering/feeding/light/soil/toxicity schedule. Per the product
 * requirement: identification accuracy comes from Plant.id's visual match
 * PLUS the user tapping to confirm the correct one of 3-5 candidates — but
 * the actual CARE FACTS that drive reminders and product recommendations
 * must come from synthesized horticultural knowledge, not a single API's
 * thin default fields.
 *
 * SOURCING METHODOLOGY (per species, target 3 source types)
 * -----------------------------------------------------------
 * 1. University / cooperative extension horticulture programs (.edu) —
 *    e.g. Clemson HGIC, University of Florida IFAS, Missouri Botanical
 *    Garden Plant Finder, Iowa State University Extension, NC State
 *    Extension Gardener Plant Toolbox, Purdue Extension.
 * 2. Established houseplant reference guides/books — e.g. "The New Plant
 *    Parent" (Darryl Cheng), "How to Grow Fresh Air" (B.C. Wolverton, NASA
 *    Clean Air Study), American Horticultural Society "Encyclopedia of
 *    Houseplants".
 * 3. Specialist grower/nursery care sheets — e.g. Costa Farms, Pistils
 *    Nursery, The Sill — used only as directional/practical detail, never
 *    as the sole source for a scheduling-critical fact.
 *
 * This build was authored without live web browsing access from inside the
 * sandbox, so every entry below is a best-effort synthesis from general
 * horticultural knowledge widely corroborated across the source types
 * above, NOT copy-pasted from a specific live page. `researchStatus` is
 * therefore "seed" for every row, and `sourceCitations` lists the
 * canonical, publicly verifiable source names/URLs a follow-up research
 * pass should open to confirm/refine exact numbers and add direct quotes
 * or per-field citations. Treat numeric ranges here as reasonable
 * "average indoor US home" defaults — the app further adjusts them per
 * plant using live location + weather (see server/care-scheduling.ts).
 *
 * FOLLOW-UP RESEARCH PROCESS (see README.md "Care data research process")
 * -------------------------------------------------------------------------
 * A dedicated research pass should, per species:
 *   1. Open each URL in `sourceCitations` and confirm the numeric ranges.
 *   2. Flip `researchStatus` to "verified" once cross-checked.
 *   3. Fill any `researchNotes` TODOs (marked "TODO(research):").
 *   4. Expand `sourceCitations` with the specific page(s) that back each
 *      field (watering vs. feeding vs. toxicity may come from different
 *      pages of the same source).
 */

import type { InsertCareProfile } from "@shared/schema";

type Seed = Omit<InsertCareProfile, "sourceCitations" | "researchStatus"> & {
  sourceCitations: { label: string; url: string }[];
};

// Shared citation pools reused across many entries (see methodology above).
const CITATIONS = {
  clemsonHGIC: { label: "Clemson Cooperative Extension, Home & Garden Information Center", url: "https://hgic.clemson.edu/" },
  ifas: { label: "University of Florida IFAS Extension", url: "https://sfyl.ifas.ufl.edu/" },
  moBotGarden: { label: "Missouri Botanical Garden Plant Finder", url: "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderSearch.aspx" },
  ncsuToolbox: { label: "NC State Extension Gardener Plant Toolbox", url: "https://plants.ces.ncsu.edu/" },
  asHouseplantEncyclopedia: { label: "American Horticultural Society, Encyclopedia of Houseplants", url: "https://ahsgardening.org/" },
  newPlantParent: { label: "Darryl Cheng, The New Plant Parent (book)", url: "https://www.houseplantjournal.com/" },
  costaFarms: { label: "Costa Farms Plant Care Guides", url: "https://www.costafarms.com/plants" },
  aspcaToxic: { label: "ASPCA Animal Poison Control, Toxic and Non-Toxic Plant List", url: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants" },
  nasaCleanAir: { label: "B.C. Wolverton, How to Grow Fresh Air / NASA Clean Air Study", url: "https://www.nasa.gov/" },
};

export const careProfileSeeds: Seed[] = [
  {
    speciesKey: "monstera-deliciosa",
    commonName: "Monstera deliciosa",
    scientificName: "Monstera deliciosa",
    waterIntervalDaysMin: 7, waterIntervalDaysMax: 10,
    waterNotes: "Water when the top 1-2 inches of soil are dry. Reduce frequency in winter dormancy.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: null,
    feedNotes: "Balanced liquid houseplant fertilizer monthly during spring/summer active growth; skip in fall/winter.",
    lightRequirement: "bright_indirect",
    placementNotes: "Bright indirect light; tolerates medium light but fenestration (leaf splits) is reduced. Keep out of direct afternoon sun.",
    soilType: "Chunky, well-draining aroid mix (bark, perlite, peat/coco coir)",
    repotIntervalMonths: 24,
    idealTempMinF: 65, idealTempMaxF: 85, idealHumidityPct: 60,
    toxicity: "Toxic to cats and dogs if ingested (insoluble calcium oxalates).",
    matureSizeNotes: "Can reach 6-8 ft indoors with support; provide a moss pole as it matures.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.newPlantParent, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "mini-monstera",
    commonName: "Mini monstera",
    scientificName: "Rhaphidophora tetrasperma",
    waterIntervalDaysMin: 7, waterIntervalDaysMax: 9,
    waterNotes: "Allow top inch of soil to dry between waterings; likes consistent moisture but not soggy roots.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: null,
    feedNotes: "Monthly balanced fertilizer during active growth; pause in winter.",
    lightRequirement: "bright_indirect",
    placementNotes: "Bright indirect light; a climbing pole encourages larger fenestrated leaves.",
    soilType: "Chunky, airy aroid mix with extra perlite/bark",
    repotIntervalMonths: 18,
    idealTempMinF: 65, idealTempMaxF: 85, idealHumidityPct: 60,
    toxicity: "Mildly toxic to pets if ingested (calcium oxalates), similar family to Monstera.",
    matureSizeNotes: "Fast-growing climbing vine; can reach several feet with support.",
    sourceCitations: [CITATIONS.costaFarms, CITATIONS.newPlantParent],
  },
  {
    speciesKey: "tree-philodendron",
    commonName: "Tree philodendron",
    scientificName: "Philodendron bipinnatifidum (Thaumatophyllum bipinnatifidum)",
    waterIntervalDaysMin: 7, waterIntervalDaysMax: 10,
    waterNotes: "Water when top 1-2 inches are dry; fairly drought tolerant once established.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: 60,
    feedNotes: "Monthly in spring/summer; every other month in fall/winter.",
    lightRequirement: "medium_to_bright_indirect",
    placementNotes: "Adapts to medium light but grows fuller in bright indirect light. Broad leaf spread needs floor space.",
    soilType: "Well-draining potting mix with added perlite/bark",
    repotIntervalMonths: 24,
    idealTempMinF: 60, idealTempMaxF: 85, idealHumidityPct: 50,
    toxicity: "Toxic to cats and dogs if ingested (calcium oxalates).",
    matureSizeNotes: "Large self-heading philodendron, can spread 4-5 ft wide indoors.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "fiddle-leaf-fig",
    commonName: "Fiddle leaf fig",
    scientificName: "Ficus lyrata",
    waterIntervalDaysMin: 6, waterIntervalDaysMax: 8,
    waterNotes: "Check top inch of soil before watering; sensitive to both under- and over-watering. Water thoroughly, then let drain fully.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: null,
    feedNotes: "Foliage fertilizer monthly at half strength during active growth (spring-summer); skip in winter.",
    lightRequirement: "bright_indirect",
    placementNotes: "Bright indirect light, rotate weekly for even growth; avoid moving/drafts which cause leaf drop.",
    soilType: "Well-draining potting mix with perlite for aeration",
    repotIntervalMonths: 24,
    idealTempMinF: 65, idealTempMaxF: 80, idealHumidityPct: 40,
    toxicity: "Toxic to cats and dogs if ingested (irritant sap with calcium oxalates).",
    matureSizeNotes: "Can reach 6-10 ft indoors; slow to moderate grower.",
    sourceCitations: [CITATIONS.clemsonHGIC, CITATIONS.newPlantParent, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "snake-plant",
    commonName: "Snake plant",
    scientificName: "Dracaena trifasciata (formerly Sansevieria trifasciata)",
    waterIntervalDaysMin: 14, waterIntervalDaysMax: 21,
    waterNotes: "Let soil dry out deeply between waterings; highly drought tolerant, most commonly killed by overwatering.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: null,
    feedNotes: "Light, quarter-to-half-strength houseplant fertilizer monthly in spring/summer only.",
    lightRequirement: "low_to_bright_indirect",
    placementNotes: "Tolerates low light but grows best in medium-bright indirect light. Very adaptable.",
    soilType: "Fast-draining succulent/cactus mix",
    repotIntervalMonths: 36,
    idealTempMinF: 60, idealTempMaxF: 85, idealHumidityPct: 30,
    toxicity: "Mildly toxic to cats and dogs if ingested (saponins) — can cause GI upset.",
    matureSizeNotes: "Upright architectural leaves typically 1-3 ft tall indoors.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.nasaCleanAir, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "golden-pothos",
    commonName: "Golden pothos",
    scientificName: "Epipremnum aureum",
    waterIntervalDaysMin: 7, waterIntervalDaysMax: 9,
    waterNotes: "Water when top 1-2 inches of soil are dry; very forgiving of missed waterings.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: 60,
    feedNotes: "Monthly in active growth; every other month in winter.",
    lightRequirement: "low_to_bright_indirect",
    placementNotes: "Extremely adaptable — low light to bright indirect; variegation fades in low light.",
    soilType: "Standard well-draining potting mix",
    repotIntervalMonths: 18,
    idealTempMinF: 60, idealTempMaxF: 85, idealHumidityPct: 40,
    toxicity: "Toxic to cats and dogs if ingested (calcium oxalates).",
    matureSizeNotes: "Trailing vine, can grow several feet long; trim to encourage fullness.",
    sourceCitations: [CITATIONS.clemsonHGIC, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "peace-lily",
    commonName: "Peace lily",
    scientificName: "Spathiphyllum wallisii",
    waterIntervalDaysMin: 6, waterIntervalDaysMax: 8,
    waterNotes: "Keep soil evenly moist; plant droops visibly when thirsty and perks up quickly after watering.",
    feedIntervalDaysActive: 42, feedIntervalDaysDormant: null,
    feedNotes: "Balanced liquid fertilizer every 6 weeks in spring/summer; skip in winter.",
    lightRequirement: "low_to_medium_indirect",
    placementNotes: "Tolerates low light, flowers best in medium indirect light. Avoid direct sun (scorches leaves).",
    soilType: "Rich, well-draining potting mix that retains some moisture",
    repotIntervalMonths: 18,
    idealTempMinF: 65, idealTempMaxF: 80, idealHumidityPct: 50,
    toxicity: "Toxic to cats and dogs if ingested (calcium oxalates).",
    matureSizeNotes: "Typically 1-3 ft tall indoors with white spathe blooms.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.nasaCleanAir, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "zz-plant",
    commonName: "ZZ plant",
    scientificName: "Zamioculcas zamiifolia",
    waterIntervalDaysMin: 14, waterIntervalDaysMax: 21,
    waterNotes: "Allow soil to dry completely; rhizomes store water, so this plant tolerates neglect well.",
    feedIntervalDaysActive: 60, feedIntervalDaysDormant: null,
    feedNotes: "Light feeding every 2 months during spring/summer; skip in winter.",
    lightRequirement: "low_to_bright_indirect",
    placementNotes: "Extremely tolerant of low light; grows faster in bright indirect light.",
    soilType: "Well-draining potting mix, cactus/succulent blend works well",
    repotIntervalMonths: 36,
    idealTempMinF: 60, idealTempMaxF: 85, idealHumidityPct: 30,
    toxicity: "Toxic to cats and dogs if ingested (calcium oxalates); sap can irritate skin.",
    matureSizeNotes: "Glossy upright stems, typically 2-3 ft tall indoors.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "rubber-plant",
    commonName: "Rubber plant",
    scientificName: "Ficus elastica",
    waterIntervalDaysMin: 7, waterIntervalDaysMax: 10,
    waterNotes: "Water when top 1-2 inches of soil are dry; sensitive to overwatering (leaf drop/yellowing).",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: null,
    feedNotes: "Monthly balanced fertilizer spring-summer; skip in winter dormancy.",
    lightRequirement: "bright_indirect",
    placementNotes: "Bright indirect light produces the deepest leaf color; wipe leaves to keep pores clear.",
    soilType: "Well-draining potting mix with perlite",
    repotIntervalMonths: 24,
    idealTempMinF: 65, idealTempMaxF: 80, idealHumidityPct: 40,
    toxicity: "Toxic to cats and dogs if ingested (irritant latex sap).",
    matureSizeNotes: "Can reach 6-10 ft indoors as a tree form.",
    sourceCitations: [CITATIONS.clemsonHGIC, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "pothos-marble-queen",
    commonName: "Marble queen pothos",
    scientificName: "Epipremnum aureum 'Marble Queen'",
    waterIntervalDaysMin: 7, waterIntervalDaysMax: 10,
    waterNotes: "Water when top 1-2 inches are dry; needs slightly more light than solid green pothos to maintain variegation.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: 60,
    feedNotes: "Monthly in active growth, every other month in winter.",
    lightRequirement: "medium_to_bright_indirect",
    placementNotes: "Brighter indirect light keeps the white variegation pronounced; low light causes reversion to green.",
    soilType: "Standard well-draining potting mix",
    repotIntervalMonths: 18,
    idealTempMinF: 60, idealTempMaxF: 85, idealHumidityPct: 40,
    toxicity: "Toxic to cats and dogs if ingested (calcium oxalates).",
    matureSizeNotes: "Trailing vine similar habit to golden pothos.",
    sourceCitations: [CITATIONS.clemsonHGIC, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "spider-plant",
    commonName: "Spider plant",
    scientificName: "Chlorophytum comosum",
    waterIntervalDaysMin: 6, waterIntervalDaysMax: 9,
    waterNotes: "Keep lightly moist; sensitive to fluoride/chlorine in tap water (brown leaf tips) — filtered water helps.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: 60,
    feedNotes: "Monthly during growth, every other month in winter.",
    lightRequirement: "medium_to_bright_indirect",
    placementNotes: "Bright indirect light produces best variegation; tolerates some direct morning sun.",
    soilType: "Standard well-draining potting mix",
    repotIntervalMonths: 18,
    idealTempMinF: 60, idealTempMaxF: 80, idealHumidityPct: 40,
    toxicity: "Non-toxic to cats and dogs (may cause mild GI upset/attracts cats but not seriously toxic).",
    matureSizeNotes: "Arching grass-like leaves, produces plantlets on runners.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.nasaCleanAir, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "chinese-money-plant",
    commonName: "Chinese money plant",
    scientificName: "Pilea peperomioides",
    waterIntervalDaysMin: 7, waterIntervalDaysMax: 9,
    waterNotes: "Let top inch of soil dry; rotate pot regularly for even, symmetrical growth.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: null,
    feedNotes: "Monthly balanced fertilizer during spring/summer; skip in winter.",
    lightRequirement: "bright_indirect",
    placementNotes: "Bright indirect light; avoid direct sun which scorches round leaves.",
    soilType: "Well-draining potting mix with perlite",
    repotIntervalMonths: 18,
    idealTempMinF: 65, idealTempMaxF: 80, idealHumidityPct: 40,
    toxicity: "Generally considered non-toxic to pets.",
    matureSizeNotes: "Compact, typically under 12 in indoors; produces easy-to-propagate offsets.",
    sourceCitations: [CITATIONS.newPlantParent, CITATIONS.costaFarms],
  },
  {
    speciesKey: "philodendron-heartleaf",
    commonName: "Heartleaf philodendron",
    scientificName: "Philodendron hederaceum",
    waterIntervalDaysMin: 7, waterIntervalDaysMax: 9,
    waterNotes: "Water when top inch is dry; very forgiving trailing plant.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: 60,
    feedNotes: "Monthly in active growth, every other month in winter.",
    lightRequirement: "low_to_bright_indirect",
    placementNotes: "Tolerates low light but grows fuller/faster in medium-bright indirect light.",
    soilType: "Standard well-draining potting mix",
    repotIntervalMonths: 18,
    idealTempMinF: 65, idealTempMaxF: 85, idealHumidityPct: 45,
    toxicity: "Toxic to cats and dogs if ingested (calcium oxalates).",
    matureSizeNotes: "Fast-growing trailing/climbing vine.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "calathea-orbifolia",
    commonName: "Calathea orbifolia",
    scientificName: "Goeppertia orbifolia",
    waterIntervalDaysMin: 5, waterIntervalDaysMax: 7,
    waterNotes: "Keep evenly moist, never soggy or bone dry; sensitive to tap water minerals/fluoride — use filtered/distilled water.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: null,
    feedNotes: "Diluted (half-strength) fertilizer monthly in spring/summer; skip in winter.",
    lightRequirement: "medium_indirect",
    placementNotes: "Medium indirect light, no direct sun; needs consistently high humidity (pebble tray/humidifier recommended).",
    soilType: "Peat-based, moisture-retentive but well-draining mix",
    repotIntervalMonths: 18,
    idealTempMinF: 65, idealTempMaxF: 80, idealHumidityPct: 60,
    toxicity: "Non-toxic to cats and dogs.",
    matureSizeNotes: "Large striped oval leaves, can reach 2-3 ft; notoriously fussy about humidity/water quality.",
    sourceCitations: [CITATIONS.asHouseplantEncyclopedia, CITATIONS.newPlantParent, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "boston-fern",
    commonName: "Boston fern",
    scientificName: "Nephrolepis exaltata",
    waterIntervalDaysMin: 3, waterIntervalDaysMax: 5,
    waterNotes: "Keep soil consistently moist; do not let dry out fully — fronds crisp quickly when underwatered.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: null,
    feedNotes: "Light monthly feeding spring-summer; skip in winter.",
    lightRequirement: "medium_indirect",
    placementNotes: "Bright, indirect light; loves high humidity (bathrooms/kitchens work well).",
    soilType: "Peat-based, moisture-retentive potting mix",
    repotIntervalMonths: 12,
    idealTempMinF: 60, idealTempMaxF: 80, idealHumidityPct: 65,
    toxicity: "Non-toxic to cats and dogs.",
    matureSizeNotes: "Arching fronds, spreads 2-3 ft; classic hanging basket plant.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.nasaCleanAir, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "aloe-vera",
    commonName: "Aloe vera",
    scientificName: "Aloe vera (Aloe barbadensis miller)",
    waterIntervalDaysMin: 14, waterIntervalDaysMax: 21,
    waterNotes: "Let soil dry completely between waterings; a classic succulent — overwatering causes root rot.",
    feedIntervalDaysActive: 60, feedIntervalDaysDormant: null,
    feedNotes: "Light cactus/succulent fertilizer 1-2 times during spring/summer; skip in winter.",
    lightRequirement: "bright_direct_to_indirect",
    placementNotes: "Bright light, tolerates some direct sun; a south/west windowsill is ideal.",
    soilType: "Fast-draining cactus/succulent mix",
    repotIntervalMonths: 24,
    idealTempMinF: 55, idealTempMaxF: 85, idealHumidityPct: 30,
    toxicity: "Mildly toxic to cats and dogs if ingested (saponins) — GI upset.",
    matureSizeNotes: "Rosette form, typically 1-2 ft; produces offset pups.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "jade-plant",
    commonName: "Jade plant",
    scientificName: "Crassula ovata",
    waterIntervalDaysMin: 14, waterIntervalDaysMax: 21,
    waterNotes: "Let soil dry fully between waterings; classic succulent, very drought tolerant.",
    feedIntervalDaysActive: 60, feedIntervalDaysDormant: null,
    feedNotes: "Diluted succulent fertilizer every 2 months in spring/summer; skip in winter.",
    lightRequirement: "bright_direct_to_indirect",
    placementNotes: "Needs several hours of bright light daily (south/west window) to stay compact and avoid legginess.",
    soilType: "Fast-draining cactus/succulent mix",
    repotIntervalMonths: 24,
    idealTempMinF: 60, idealTempMaxF: 85, idealHumidityPct: 30,
    toxicity: "Toxic to cats and dogs if ingested (unknown compound, causes vomiting/lethargy).",
    matureSizeNotes: "Thick woody stems, can reach 2-3 ft, tree-like with age.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "pothos-neon",
    commonName: "Neon pothos",
    scientificName: "Epipremnum aureum 'Neon'",
    waterIntervalDaysMin: 7, waterIntervalDaysMax: 9,
    waterNotes: "Water when top 1-2 inches dry; chartreuse color is brightest in more light.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: 60,
    feedNotes: "Monthly active season, every other month in winter.",
    lightRequirement: "medium_to_bright_indirect",
    placementNotes: "Brighter indirect light keeps foliage vivid chartreuse; low light causes it to green out.",
    soilType: "Standard well-draining potting mix",
    repotIntervalMonths: 18,
    idealTempMinF: 60, idealTempMaxF: 85, idealHumidityPct: 40,
    toxicity: "Toxic to cats and dogs if ingested (calcium oxalates).",
    matureSizeNotes: "Trailing vine, similar habit to golden pothos.",
    sourceCitations: [CITATIONS.clemsonHGIC, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "dracaena-marginata",
    commonName: "Dragon tree",
    scientificName: "Dracaena marginata",
    waterIntervalDaysMin: 10, waterIntervalDaysMax: 14,
    waterNotes: "Allow soil to dry out between waterings; sensitive to fluoride in tap water (brown leaf tips).",
    feedIntervalDaysActive: 45, feedIntervalDaysDormant: null,
    feedNotes: "Light feeding every 6 weeks spring-summer; skip in winter.",
    lightRequirement: "medium_to_bright_indirect",
    placementNotes: "Tolerates medium light, best color in bright indirect light; avoid direct sun.",
    soilType: "Well-draining potting mix with perlite",
    repotIntervalMonths: 24,
    idealTempMinF: 65, idealTempMaxF: 80, idealHumidityPct: 40,
    toxicity: "Toxic to cats and dogs if ingested (saponins).",
    matureSizeNotes: "Slow-growing, can reach 6+ ft indoors with slender arching leaves.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "bird-of-paradise",
    commonName: "Bird of paradise",
    scientificName: "Strelitzia nicolai",
    waterIntervalDaysMin: 7, waterIntervalDaysMax: 10,
    waterNotes: "Water when top 1-2 inches are dry; thrives with consistent moisture in active growth.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: 60,
    feedNotes: "Monthly balanced fertilizer in spring/summer, every other month in winter.",
    lightRequirement: "bright_indirect_to_direct",
    placementNotes: "Needs bright light, tolerates some direct sun; rotate for even growth.",
    soilType: "Rich, well-draining potting mix",
    repotIntervalMonths: 24,
    idealTempMinF: 65, idealTempMaxF: 85, idealHumidityPct: 50,
    toxicity: "Mildly toxic to cats and dogs if ingested (GI upset).",
    matureSizeNotes: "Large architectural plant, can reach 6-8+ ft indoors.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "english-ivy",
    commonName: "English ivy",
    scientificName: "Hedera helix",
    waterIntervalDaysMin: 6, waterIntervalDaysMax: 8,
    waterNotes: "Keep soil lightly moist; likes more humidity than average.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: 60,
    feedNotes: "Monthly during growth, every other month in winter.",
    lightRequirement: "medium_to_bright_indirect",
    placementNotes: "Bright indirect light; good air circulation reduces spider mite risk.",
    soilType: "Standard well-draining potting mix",
    repotIntervalMonths: 18,
    idealTempMinF: 55, idealTempMaxF: 80, idealHumidityPct: 45,
    toxicity: "Toxic to cats and dogs if ingested.",
    matureSizeNotes: "Trailing/climbing vine, several feet long when mature.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.nasaCleanAir, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "peperomia-obtusifolia",
    commonName: "Baby rubber plant (Peperomia)",
    scientificName: "Peperomia obtusifolia",
    waterIntervalDaysMin: 9, waterIntervalDaysMax: 12,
    waterNotes: "Let soil dry between waterings; semi-succulent leaves store water, prone to rot if overwatered.",
    feedIntervalDaysActive: 45, feedIntervalDaysDormant: null,
    feedNotes: "Light feeding every 6 weeks in spring/summer; skip in winter.",
    lightRequirement: "medium_indirect",
    placementNotes: "Medium to bright indirect light; compact size suits desks/shelves.",
    soilType: "Well-draining potting mix with perlite",
    repotIntervalMonths: 24,
    idealTempMinF: 65, idealTempMaxF: 80, idealHumidityPct: 45,
    toxicity: "Non-toxic to cats and dogs.",
    matureSizeNotes: "Compact, typically under 12 in.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "anthurium-andraeanum",
    commonName: "Anthurium (flamingo flower)",
    scientificName: "Anthurium andraeanum",
    waterIntervalDaysMin: 7, waterIntervalDaysMax: 9,
    waterNotes: "Water when top inch of soil is dry; likes humidity but not soggy roots.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: 60,
    feedNotes: "Monthly balanced/bloom fertilizer spring-summer; every other month in winter.",
    lightRequirement: "medium_to_bright_indirect",
    placementNotes: "Bright indirect light encourages more blooms; avoid direct sun.",
    soilType: "Chunky, well-draining aroid mix",
    repotIntervalMonths: 18,
    idealTempMinF: 65, idealTempMaxF: 85, idealHumidityPct: 60,
    toxicity: "Toxic to cats and dogs if ingested (calcium oxalates).",
    matureSizeNotes: "Typically 1-2 ft; blooms glossy red/pink spathes when happy.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "areca-palm",
    commonName: "Areca palm",
    scientificName: "Dypsis lutescens",
    waterIntervalDaysMin: 7, waterIntervalDaysMax: 9,
    waterNotes: "Keep soil lightly moist; sensitive to both drought stress and overwatering root rot.",
    feedIntervalDaysActive: 45, feedIntervalDaysDormant: null,
    feedNotes: "Palm-specific fertilizer every 6 weeks in spring/summer; skip in winter.",
    lightRequirement: "bright_indirect",
    placementNotes: "Bright indirect light; benefits from higher humidity and occasional misting.",
    soilType: "Well-draining potting mix with peat and perlite",
    repotIntervalMonths: 24,
    idealTempMinF: 65, idealTempMaxF: 85, idealHumidityPct: 50,
    toxicity: "Non-toxic to cats and dogs — a pet-safe palm option.",
    matureSizeNotes: "Can reach 6-7 ft indoors, clumping habit.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.nasaCleanAir, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "christmas-cactus",
    commonName: "Christmas cactus",
    scientificName: "Schlumbergera bridgesii",
    waterIntervalDaysMin: 10, waterIntervalDaysMax: 14,
    waterNotes: "Let top inch dry between waterings; more moisture-loving than desert cacti. Reduce watering after bloom for dormancy.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: null,
    feedNotes: "Balanced fertilizer monthly spring-summer; switch to bloom fertilizer in fall bud set; skip in winter rest.",
    lightRequirement: "medium_to_bright_indirect",
    placementNotes: "Bright indirect light; needs cooler temps and long dark nights in fall to set buds.",
    soilType: "Well-draining potting mix with extra perlite (not desert cactus mix — retains more moisture)",
    repotIntervalMonths: 24,
    idealTempMinF: 60, idealTempMaxF: 75, idealHumidityPct: 45,
    toxicity: "Non-toxic to cats and dogs.",
    matureSizeNotes: "Trailing segmented stems, typically 12-24 in.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "parlor-palm",
    commonName: "Parlor palm",
    scientificName: "Chamaedorea elegans",
    waterIntervalDaysMin: 8, waterIntervalDaysMax: 10,
    waterNotes: "Keep lightly moist; let top inch dry before watering again.",
    feedIntervalDaysActive: 45, feedIntervalDaysDormant: null,
    feedNotes: "Light palm fertilizer every 6 weeks in spring/summer; skip in winter.",
    lightRequirement: "low_to_medium_indirect",
    placementNotes: "Tolerates low light well, a good low-maintenance office palm.",
    soilType: "Well-draining potting mix",
    repotIntervalMonths: 24,
    idealTempMinF: 65, idealTempMaxF: 80, idealHumidityPct: 45,
    toxicity: "Non-toxic to cats and dogs — a pet-safe palm option.",
    matureSizeNotes: "Compact, typically 2-4 ft indoors, slow growing.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.nasaCleanAir, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "african-violet",
    commonName: "African violet",
    scientificName: "Saintpaulia ionantha",
    waterIntervalDaysMin: 5, waterIntervalDaysMax: 7,
    waterNotes: "Keep soil evenly moist but not wet; water from below or avoid wetting fuzzy leaves to prevent spotting.",
    feedIntervalDaysActive: 14, feedIntervalDaysDormant: 30,
    feedNotes: "Dilute African-violet-specific fertilizer every 2 weeks in bloom season; monthly in winter.",
    lightRequirement: "medium_indirect",
    placementNotes: "Bright indirect light (east-facing window ideal); avoid direct sun which scorches leaves.",
    soilType: "Light, well-draining African violet potting mix",
    repotIntervalMonths: 12,
    idealTempMinF: 65, idealTempMaxF: 80, idealHumidityPct: 50,
    toxicity: "Non-toxic to cats and dogs.",
    matureSizeNotes: "Compact rosette, typically under 12 in, repeat-blooming.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "orchid-phalaenopsis",
    commonName: "Moth orchid",
    scientificName: "Phalaenopsis spp.",
    waterIntervalDaysMin: 7, waterIntervalDaysMax: 10,
    waterNotes: "Water thoroughly then allow to nearly dry (ice cube or weekly soak methods both work); never let roots sit in water.",
    feedIntervalDaysActive: 14, feedIntervalDaysDormant: 30,
    feedNotes: "Weak orchid-specific fertilizer every 2 weeks in active growth; monthly during rest.",
    lightRequirement: "medium_bright_indirect",
    placementNotes: "Bright indirect light (east/north window); needs a dip in nighttime temp to trigger reblooming.",
    soilType: "Specialized orchid bark/moss mix — never standard potting soil",
    repotIntervalMonths: 18,
    idealTempMinF: 65, idealTempMaxF: 80, idealHumidityPct: 55,
    toxicity: "Non-toxic to cats and dogs.",
    matureSizeNotes: "Arching flower spikes, blooms last 2-3 months.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "succulent-echeveria",
    commonName: "Echeveria (rosette succulent)",
    scientificName: "Echeveria spp.",
    waterIntervalDaysMin: 12, waterIntervalDaysMax: 18,
    waterNotes: "Soak-and-dry method: water thoroughly then let dry completely; very susceptible to rot if kept wet.",
    feedIntervalDaysActive: 60, feedIntervalDaysDormant: null,
    feedNotes: "Light succulent fertilizer 1-2 times per growing season; skip in winter.",
    lightRequirement: "bright_direct_to_indirect",
    placementNotes: "Needs several hours of bright light daily to prevent stretching/etiolation.",
    soilType: "Fast-draining cactus/succulent mix",
    repotIntervalMonths: 24,
    idealTempMinF: 60, idealTempMaxF: 85, idealHumidityPct: 30,
    toxicity: "Generally non-toxic to cats and dogs.",
    matureSizeNotes: "Compact rosette form, typically under 6 in.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "haworthia",
    commonName: "Haworthia (zebra plant)",
    scientificName: "Haworthiopsis attenuata",
    waterIntervalDaysMin: 14, waterIntervalDaysMax: 21,
    waterNotes: "Let soil dry fully between waterings; small succulent, easy to overwater.",
    feedIntervalDaysActive: 60, feedIntervalDaysDormant: null,
    feedNotes: "Light succulent feeding 1-2 times per growing season.",
    lightRequirement: "medium_bright_indirect",
    placementNotes: "Bright indirect light; direct hot sun can scorch — unlike some succulents it prefers filtered light.",
    soilType: "Fast-draining cactus/succulent mix",
    repotIntervalMonths: 24,
    idealTempMinF: 60, idealTempMaxF: 85, idealHumidityPct: 30,
    toxicity: "Non-toxic to cats and dogs.",
    matureSizeNotes: "Small rosette, typically under 5 in, offsets readily.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "philodendron-brasil",
    commonName: "Philodendron Brasil",
    scientificName: "Philodendron hederaceum 'Brasil'",
    waterIntervalDaysMin: 7, waterIntervalDaysMax: 9,
    waterNotes: "Water when top inch is dry; forgiving trailing plant similar to heartleaf philodendron.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: 60,
    feedNotes: "Monthly in active growth, every other month in winter.",
    lightRequirement: "medium_to_bright_indirect",
    placementNotes: "Brighter indirect light keeps the yellow-green variegation vivid.",
    soilType: "Standard well-draining potting mix",
    repotIntervalMonths: 18,
    idealTempMinF: 65, idealTempMaxF: 85, idealHumidityPct: 45,
    toxicity: "Toxic to cats and dogs if ingested (calcium oxalates).",
    matureSizeNotes: "Fast-growing trailing vine.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "croton",
    commonName: "Croton",
    scientificName: "Codiaeum variegatum",
    waterIntervalDaysMin: 6, waterIntervalDaysMax: 8,
    waterNotes: "Keep soil consistently moist; sensitive to both drought and cold drafts (leaf drop).",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: 60,
    feedNotes: "Monthly balanced fertilizer in spring/summer; every other month in winter.",
    lightRequirement: "bright_direct_to_indirect",
    placementNotes: "Needs bright light (some direct sun) to maintain vivid leaf coloration.",
    soilType: "Well-draining potting mix",
    repotIntervalMonths: 18,
    idealTempMinF: 65, idealTempMaxF: 85, idealHumidityPct: 50,
    toxicity: "Toxic to cats and dogs if ingested (irritant sap).",
    matureSizeNotes: "Colorful leathery leaves, typically 2-4 ft indoors.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "calathea-medallion",
    commonName: "Calathea medallion",
    scientificName: "Goeppertia veitchiana 'Medallion'",
    waterIntervalDaysMin: 5, waterIntervalDaysMax: 7,
    waterNotes: "Keep evenly moist with filtered/distilled water; sensitive to tap water minerals.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: null,
    feedNotes: "Half-strength fertilizer monthly in spring/summer; skip in winter.",
    lightRequirement: "medium_indirect",
    placementNotes: "Medium indirect light, no direct sun; high humidity essential (leaves curl when dry air).",
    soilType: "Peat-based, moisture-retentive well-draining mix",
    repotIntervalMonths: 18,
    idealTempMinF: 65, idealTempMaxF: 80, idealHumidityPct: 60,
    toxicity: "Non-toxic to cats and dogs.",
    matureSizeNotes: "Ornately patterned round leaves, typically 1-2 ft.",
    sourceCitations: [CITATIONS.asHouseplantEncyclopedia, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "money-tree",
    commonName: "Money tree",
    scientificName: "Pachira aquatica",
    waterIntervalDaysMin: 9, waterIntervalDaysMax: 12,
    waterNotes: "Allow top 1-2 inches to dry; sensitive to overwatering despite aquatic origin/common name.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: 60,
    feedNotes: "Monthly balanced fertilizer spring-summer; every other month in winter.",
    lightRequirement: "medium_to_bright_indirect",
    placementNotes: "Bright indirect light; braided trunk forms tolerate lower light than most.",
    soilType: "Well-draining potting mix",
    repotIntervalMonths: 24,
    idealTempMinF: 65, idealTempMaxF: 85, idealHumidityPct: 50,
    toxicity: "Non-toxic to cats and dogs.",
    matureSizeNotes: "Can reach 6-8 ft indoors with braided trunk.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "ponytail-palm",
    commonName: "Ponytail palm",
    scientificName: "Beaucarnea recurvata",
    waterIntervalDaysMin: 14, waterIntervalDaysMax: 21,
    waterNotes: "Let soil dry fully; bulbous caudex stores water, tolerates significant drought.",
    feedIntervalDaysActive: 60, feedIntervalDaysDormant: null,
    feedNotes: "Light feeding every 2 months during spring/summer; skip in winter.",
    lightRequirement: "bright_direct_to_indirect",
    placementNotes: "Needs bright light, tolerates direct sun; a sunny window is ideal.",
    soilType: "Fast-draining cactus/succulent mix",
    repotIntervalMonths: 36,
    idealTempMinF: 60, idealTempMaxF: 85, idealHumidityPct: 30,
    toxicity: "Non-toxic to cats and dogs.",
    matureSizeNotes: "Distinctive swollen base, can reach several feet indoors.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "prayer-plant",
    commonName: "Prayer plant",
    scientificName: "Maranta leuconeura",
    waterIntervalDaysMin: 5, waterIntervalDaysMax: 7,
    waterNotes: "Keep evenly moist with filtered water; leaves fold up at night (nyctinasty) — a normal trait, not distress.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: null,
    feedNotes: "Half-strength fertilizer monthly spring-summer; skip in winter.",
    lightRequirement: "low_to_medium_indirect",
    placementNotes: "Medium indirect light, tolerates lower light; high humidity keeps leaf edges from browning.",
    soilType: "Peat-based, moisture-retentive well-draining mix",
    repotIntervalMonths: 18,
    idealTempMinF: 65, idealTempMaxF: 80, idealHumidityPct: 55,
    toxicity: "Non-toxic to cats and dogs.",
    matureSizeNotes: "Low, spreading habit, typically under 12 in.",
    sourceCitations: [CITATIONS.asHouseplantEncyclopedia, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "philodendron-birkin",
    commonName: "Philodendron Birkin",
    scientificName: "Philodendron 'Birkin'",
    waterIntervalDaysMin: 7, waterIntervalDaysMax: 9,
    waterNotes: "Water when top inch is dry; keep an eye on new leaves which emerge solid green before pinstripes develop.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: 60,
    feedNotes: "Monthly in active growth, every other month in winter.",
    lightRequirement: "medium_to_bright_indirect",
    placementNotes: "Bright indirect light keeps variegated pinstripe pattern crisp.",
    soilType: "Chunky, well-draining aroid mix",
    repotIntervalMonths: 18,
    idealTempMinF: 65, idealTempMaxF: 85, idealHumidityPct: 50,
    toxicity: "Toxic to cats and dogs if ingested (calcium oxalates).",
    matureSizeNotes: "Compact, non-climbing, typically under 2 ft.",
    sourceCitations: [CITATIONS.costaFarms, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "alocasia-polly",
    commonName: "Alocasia Polly (African mask plant)",
    scientificName: "Alocasia x amazonica 'Polly'",
    waterIntervalDaysMin: 6, waterIntervalDaysMax: 8,
    waterNotes: "Keep soil moist but not soggy; goes dormant in winter — reduce watering significantly then.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: null,
    feedNotes: "Half-strength fertilizer monthly in spring/summer; withhold during winter dormancy.",
    lightRequirement: "medium_bright_indirect",
    placementNotes: "Bright indirect light, no direct sun; needs high humidity, prone to spider mites in dry air.",
    soilType: "Chunky, well-draining aroid mix",
    repotIntervalMonths: 18,
    idealTempMinF: 65, idealTempMaxF: 85, idealHumidityPct: 60,
    toxicity: "Toxic to cats and dogs if ingested (calcium oxalates).",
    matureSizeNotes: "Arrow-shaped leaves with white veins, typically 1-2 ft; can die back to tuber in winter and regrow.",
    sourceCitations: [CITATIONS.asHouseplantEncyclopedia, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "philodendron-xanadu",
    commonName: "Philodendron Xanadu",
    scientificName: "Thaumatophyllum xanadu",
    waterIntervalDaysMin: 7, waterIntervalDaysMax: 10,
    waterNotes: "Water when top 1-2 inches are dry; fairly forgiving.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: 60,
    feedNotes: "Monthly in active growth, every other month in winter.",
    lightRequirement: "medium_to_bright_indirect",
    placementNotes: "Medium to bright indirect light; compact mounding habit good for floor or large pots.",
    soilType: "Well-draining potting mix with added perlite/bark",
    repotIntervalMonths: 24,
    idealTempMinF: 60, idealTempMaxF: 85, idealHumidityPct: 45,
    toxicity: "Toxic to cats and dogs if ingested (calcium oxalates).",
    matureSizeNotes: "Mounding habit, spreads 2-3 ft wide.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "fern-maidenhair",
    commonName: "Maidenhair fern",
    scientificName: "Adiantum raddianum",
    waterIntervalDaysMin: 3, waterIntervalDaysMax: 4,
    waterNotes: "Keep soil consistently moist at all times; extremely sensitive to drying out (fronds die back quickly).",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: null,
    feedNotes: "Light monthly feeding in spring/summer; skip in winter.",
    lightRequirement: "medium_indirect",
    placementNotes: "Bright indirect light, no direct sun; needs very high humidity — a terrarium or bathroom suits it well.",
    soilType: "Peat-based, highly moisture-retentive mix",
    repotIntervalMonths: 12,
    idealTempMinF: 65, idealTempMaxF: 80, idealHumidityPct: 70,
    toxicity: "Non-toxic to cats and dogs.",
    matureSizeNotes: "Delicate fronds, typically under 18 in; considered a finicky/advanced-care fern.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "hoya-carnosa",
    commonName: "Hoya (wax plant)",
    scientificName: "Hoya carnosa",
    waterIntervalDaysMin: 10, waterIntervalDaysMax: 14,
    waterNotes: "Let soil dry out between waterings; semi-succulent leaves store water, prone to rot if overwatered.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: null,
    feedNotes: "Diluted bloom fertilizer monthly during active growth; skip in winter.",
    lightRequirement: "bright_indirect",
    placementNotes: "Bright indirect light with some direct morning sun encourages blooming clusters.",
    soilType: "Chunky, well-draining mix (orchid bark + perlite blend works well)",
    repotIntervalMonths: 24,
    idealTempMinF: 65, idealTempMaxF: 85, idealHumidityPct: 50,
    toxicity: "Generally non-toxic to cats and dogs (mildly irritating sap).",
    matureSizeNotes: "Trailing/climbing vine, can grow several feet; blooms fragrant star-shaped flower clusters when mature.",
    sourceCitations: [CITATIONS.asHouseplantEncyclopedia, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "philodendron-pink-princess",
    commonName: "Pink princess philodendron",
    scientificName: "Philodendron erubescens 'Pink Princess'",
    waterIntervalDaysMin: 7, waterIntervalDaysMax: 9,
    waterNotes: "Water when top inch is dry; avoid overwatering which can cause stem rot at variegated sections.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: 60,
    feedNotes: "Monthly in active growth, every other month in winter.",
    lightRequirement: "bright_indirect",
    placementNotes: "Bright indirect light maximizes pink variegation; too little light reduces pink coloring.",
    soilType: "Chunky, well-draining aroid mix",
    repotIntervalMonths: 18,
    idealTempMinF: 65, idealTempMaxF: 85, idealHumidityPct: 55,
    toxicity: "Toxic to cats and dogs if ingested (calcium oxalates).",
    matureSizeNotes: "Climbing vine, variegation pattern varies per leaf/cutting.",
    sourceCitations: [CITATIONS.newPlantParent, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "succulent-string-of-pearls",
    commonName: "String of pearls",
    scientificName: "Curio rowleyanus (Senecio rowleyanus)",
    waterIntervalDaysMin: 10, waterIntervalDaysMax: 14,
    waterNotes: "Soak-and-dry; let soil dry fully — bead-like leaves store water and rot easily if overwatered.",
    feedIntervalDaysActive: 60, feedIntervalDaysDormant: null,
    feedNotes: "Light succulent fertilizer 1-2 times per growing season.",
    lightRequirement: "bright_indirect_to_some_direct",
    placementNotes: "Bright light, tolerates some direct sun; best in a hanging basket to let strands trail.",
    soilType: "Fast-draining cactus/succulent mix",
    repotIntervalMonths: 24,
    idealTempMinF: 60, idealTempMaxF: 85, idealHumidityPct: 30,
    toxicity: "Toxic to cats and dogs if ingested (contains pyrrolizidine-type compounds — GI upset).",
    matureSizeNotes: "Trailing bead-like strands, can reach several feet long.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "philodendron-selloum",
    commonName: "Philodendron Selloum",
    scientificName: "Thaumatophyllum bipinnatifidum (syn. Philodendron selloum)",
    waterIntervalDaysMin: 7, waterIntervalDaysMax: 10,
    waterNotes: "Same care profile as tree philodendron — water when top 1-2 inches dry.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: 60,
    feedNotes: "Monthly in spring/summer; every other month in fall/winter.",
    lightRequirement: "medium_to_bright_indirect",
    placementNotes: "Adapts to medium light, fuller in bright indirect light; needs floor space as it matures.",
    soilType: "Well-draining potting mix with added perlite/bark",
    repotIntervalMonths: 24,
    idealTempMinF: 60, idealTempMaxF: 85, idealHumidityPct: 50,
    toxicity: "Toxic to cats and dogs if ingested (calcium oxalates).",
    matureSizeNotes: "Large self-heading philodendron, spreads several feet wide.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "kentia-palm",
    commonName: "Kentia palm",
    scientificName: "Howea forsteriana",
    waterIntervalDaysMin: 9, waterIntervalDaysMax: 12,
    waterNotes: "Let top inch dry between waterings; sensitive to both extremes.",
    feedIntervalDaysActive: 45, feedIntervalDaysDormant: null,
    feedNotes: "Palm-specific fertilizer every 6 weeks spring-summer; skip in winter.",
    lightRequirement: "low_to_bright_indirect",
    placementNotes: "Tolerates lower light well; a classic elegant low-maintenance interior palm.",
    soilType: "Well-draining potting mix",
    repotIntervalMonths: 36,
    idealTempMinF: 65, idealTempMaxF: 80, idealHumidityPct: 45,
    toxicity: "Non-toxic to cats and dogs.",
    matureSizeNotes: "Slow growing, can reach 6-10 ft indoors over many years.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "philodendron-congo",
    commonName: "Philodendron Congo",
    scientificName: "Philodendron 'Congo'",
    waterIntervalDaysMin: 7, waterIntervalDaysMax: 10,
    waterNotes: "Water when top 1-2 inches dry; larger leaves show wilting clearly when thirsty.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: 60,
    feedNotes: "Monthly in active growth, every other month in winter.",
    lightRequirement: "medium_to_bright_indirect",
    placementNotes: "Medium to bright indirect light; non-climbing upright form.",
    soilType: "Well-draining potting mix with perlite",
    repotIntervalMonths: 24,
    idealTempMinF: 65, idealTempMaxF: 85, idealHumidityPct: 45,
    toxicity: "Toxic to cats and dogs if ingested (calcium oxalates).",
    matureSizeNotes: "Upright clumping form, typically 2-3 ft.",
    sourceCitations: [CITATIONS.costaFarms, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "cast-iron-plant",
    commonName: "Cast iron plant",
    scientificName: "Aspidistra elatior",
    waterIntervalDaysMin: 10, waterIntervalDaysMax: 14,
    waterNotes: "Let top 1-2 inches dry; extremely tolerant of neglect and inconsistent watering.",
    feedIntervalDaysActive: 60, feedIntervalDaysDormant: null,
    feedNotes: "Light feeding every 2 months in spring/summer; skip in winter.",
    lightRequirement: "low_indirect",
    placementNotes: "One of the most shade-tolerant houseplants; avoid direct sun which scorches leaves.",
    soilType: "Standard well-draining potting mix",
    repotIntervalMonths: 36,
    idealTempMinF: 55, idealTempMaxF: 85, idealHumidityPct: 35,
    toxicity: "Non-toxic to cats and dogs.",
    matureSizeNotes: "Slow-growing, upright dark green leaves, typically 1-2 ft.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "philodendron-micans",
    commonName: "Philodendron Micans",
    scientificName: "Philodendron hederaceum var. hederaceum",
    waterIntervalDaysMin: 7, waterIntervalDaysMax: 9,
    waterNotes: "Water when top inch is dry; velvety leaves bruise easily so handle gently.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: 60,
    feedNotes: "Monthly in active growth, every other month in winter.",
    lightRequirement: "medium_to_bright_indirect",
    placementNotes: "Bright indirect light enhances the iridescent bronze-green velvet sheen.",
    soilType: "Standard well-draining potting mix",
    repotIntervalMonths: 18,
    idealTempMinF: 65, idealTempMaxF: 85, idealHumidityPct: 50,
    toxicity: "Toxic to cats and dogs if ingested (calcium oxalates).",
    matureSizeNotes: "Trailing vine with velvety heart-shaped leaves.",
    sourceCitations: [CITATIONS.newPlantParent, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "swiss-cheese-vine",
    commonName: "Swiss cheese vine",
    scientificName: "Monstera adansonii",
    waterIntervalDaysMin: 6, waterIntervalDaysMax: 8,
    waterNotes: "Water when top inch is dry; likes consistent moisture more than Monstera deliciosa.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: null,
    feedNotes: "Monthly balanced fertilizer in spring/summer; skip in winter.",
    lightRequirement: "medium_to_bright_indirect",
    placementNotes: "Bright indirect light; a moss pole or trellis encourages larger fenestrated leaves.",
    soilType: "Chunky, well-draining aroid mix",
    repotIntervalMonths: 18,
    idealTempMinF: 65, idealTempMaxF: 85, idealHumidityPct: 55,
    toxicity: "Toxic to cats and dogs if ingested (calcium oxalates).",
    matureSizeNotes: "Fast-growing vine with fenestrated (holey) leaves.",
    sourceCitations: [CITATIONS.newPlantParent, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "fittonia",
    commonName: "Nerve plant",
    scientificName: "Fittonia albivenis",
    waterIntervalDaysMin: 4, waterIntervalDaysMax: 6,
    waterNotes: "Keep soil consistently moist; dramatically wilts when dry but usually recovers quickly after watering.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: null,
    feedNotes: "Light monthly feeding in spring/summer; skip in winter.",
    lightRequirement: "low_to_medium_indirect",
    placementNotes: "Medium indirect light, no direct sun; loves humidity — great terrarium candidate.",
    soilType: "Peat-based, moisture-retentive mix",
    repotIntervalMonths: 12,
    idealTempMinF: 65, idealTempMaxF: 80, idealHumidityPct: 65,
    toxicity: "Non-toxic to cats and dogs.",
    matureSizeNotes: "Low, spreading habit with vividly veined leaves, typically under 6 in.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "bromeliad-guzmania",
    commonName: "Bromeliad (Guzmania)",
    scientificName: "Guzmania lingulata",
    waterIntervalDaysMin: 7, waterIntervalDaysMax: 10,
    waterNotes: "Keep the central cup filled with fresh water (flush monthly), keep soil lightly moist.",
    feedIntervalDaysActive: 45, feedIntervalDaysDormant: null,
    feedNotes: "Very light diluted fertilizer in the central cup or soil every 6 weeks during growth; most nutrients absorbed via leaves.",
    lightRequirement: "medium_bright_indirect",
    placementNotes: "Bright indirect light, no direct sun; mother plant dies after blooming but produces offset pups.",
    soilType: "Light, well-draining epiphyte-friendly mix (orchid bark blend)",
    repotIntervalMonths: 12,
    idealTempMinF: 65, idealTempMaxF: 85, idealHumidityPct: 55,
    toxicity: "Non-toxic to cats and dogs.",
    matureSizeNotes: "Rosette form with a colorful central bract bloom, typically 1-2 ft.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "philodendron-lemon-lime",
    commonName: "Philodendron Lemon Lime",
    scientificName: "Philodendron hederaceum 'Lemon Lime'",
    waterIntervalDaysMin: 7, waterIntervalDaysMax: 9,
    waterNotes: "Water when top inch is dry; a forgiving trailing philodendron.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: 60,
    feedNotes: "Monthly in active growth, every other month in winter.",
    lightRequirement: "medium_to_bright_indirect",
    placementNotes: "Brighter indirect light keeps chartreuse color vivid; too little light causes greening/legginess.",
    soilType: "Standard well-draining potting mix",
    repotIntervalMonths: 18,
    idealTempMinF: 65, idealTempMaxF: 85, idealHumidityPct: 45,
    toxicity: "Toxic to cats and dogs if ingested (calcium oxalates).",
    matureSizeNotes: "Fast-growing trailing vine.",
    sourceCitations: [CITATIONS.costaFarms, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "yucca-cane",
    commonName: "Yucca cane",
    scientificName: "Yucca elephantipes (Yucca gigantea)",
    waterIntervalDaysMin: 14, waterIntervalDaysMax: 21,
    waterNotes: "Allow soil to dry out fully; very drought tolerant, prone to root rot if overwatered.",
    feedIntervalDaysActive: 60, feedIntervalDaysDormant: null,
    feedNotes: "Light feeding every 2 months spring-summer; skip in winter.",
    lightRequirement: "bright_direct_to_indirect",
    placementNotes: "Needs bright light, tolerates direct sun; a sunny spot keeps growth compact.",
    soilType: "Fast-draining cactus/succulent-style mix",
    repotIntervalMonths: 36,
    idealTempMinF: 60, idealTempMaxF: 85, idealHumidityPct: 30,
    toxicity: "Toxic to cats and dogs if ingested (saponins).",
    matureSizeNotes: "Woody cane trunk with sword-like leaf rosettes, can reach 6+ ft indoors.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "philodendron-moonlight",
    commonName: "Philodendron Moonlight",
    scientificName: "Philodendron 'Moonlight'",
    waterIntervalDaysMin: 7, waterIntervalDaysMax: 9,
    waterNotes: "Water when top inch is dry; non-climbing, compact rosette form.",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: 60,
    feedNotes: "Monthly in active growth, every other month in winter.",
    lightRequirement: "medium_to_bright_indirect",
    placementNotes: "Bright indirect light keeps the chartreuse new growth vivid.",
    soilType: "Well-draining potting mix with perlite",
    repotIntervalMonths: 18,
    idealTempMinF: 65, idealTempMaxF: 85, idealHumidityPct: 50,
    toxicity: "Toxic to cats and dogs if ingested (calcium oxalates).",
    matureSizeNotes: "Compact, non-climbing, typically under 18 in.",
    sourceCitations: [CITATIONS.costaFarms, CITATIONS.aspcaToxic],
  },
  {
    speciesKey: "umbrella-plant-schefflera",
    commonName: "Umbrella plant (Schefflera)",
    scientificName: "Schefflera arboricola",
    waterIntervalDaysMin: 9, waterIntervalDaysMax: 12,
    waterNotes: "Let top 1-2 inches dry; sensitive to overwatering (leaf drop and root rot).",
    feedIntervalDaysActive: 30, feedIntervalDaysDormant: 60,
    feedNotes: "Monthly balanced fertilizer spring-summer; every other month in winter.",
    lightRequirement: "medium_to_bright_indirect",
    placementNotes: "Bright indirect light; tolerates medium light but grows leggy.",
    soilType: "Well-draining potting mix",
    repotIntervalMonths: 24,
    idealTempMinF: 60, idealTempMaxF: 85, idealHumidityPct: 45,
    toxicity: "Toxic to cats and dogs if ingested (calcium oxalates).",
    matureSizeNotes: "Can reach 6-8 ft indoors with distinctive umbrella-like leaflet clusters.",
    sourceCitations: [CITATIONS.ifas, CITATIONS.aspcaToxic],
  },
];

// TODO(research): expand beyond this ~46-species v1 seed list toward the
// target 40-60 with additional common cultivars (e.g. more Calathea/Alocasia
// varieties, additional cacti, more palm species) once the dedicated
// research pass is scheduled. Also verify every numeric range above against
// the cited sources and mark `researchStatus: "verified"` per row as this
// happens (see README.md "Care data research process").
